export const endpoints = {
  DELETE_ADDESS_BY_USERID: '/api/persons/addresses/:id',
  DELETE_PERSON_BY_USERID: '/api/persons/:id',
  GET_ME: '/api/persons/me',
  GET_ONE_BY_USERID: '/api/persons/:id',
  GET_POSITION: '/api/persons/current-address',
  GET_PERSONS: '/api/persons',
  GET_CONFIG: '/api/persons/config',
  GET_VIRTUAL_MONEY: '/api/people/virtual-money',
  POST_PERSON_NEW: '/api/persons',
  POST_PERSON_SUPER_ADMIN: '/api/persons/super-admin',
  POST_PERSON_BLACK_LIST: '/api/persons/:id/add-to-black-list',
  POST_PERSON_REGISTER: '/api/persons/register-with-email-and-password',
  PUT_ADDRESS_BY_PERSON_ID: '/api/persons/addresses/:id',
  PUT_PERSON_BY_ID: '/api/persons/:id',
};
